name: Updater Helper

on:
  workflow_dispatch:

jobs:
  Updating:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set date variable
        run: echo "DATE=$(date +'%Y/%m/%d')" >> $GITHUB_ENV

      # 📢 Send Telegram Message
      - name: Send update message with buttons
        run: |
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage" \
            -d chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
            -d message_thread_id="${{ secrets.TELEGRAM_THREAD_LICHUI }}" \
            -d parse_mode=HTML \
            --data-urlencode "text=🚀<b>NEW UPDATE [${{ env.DATE }}]</b>🚀

            OneUI8.5 beta <b>SM-S711B</b>
            
            Thank you for using <b>LichUI ❤</b>

            © 2025 MrDemonc" \
            -d reply_markup='{
              "inline_keyboard": [
                [
                  { "text": "📥 Download", "url": "https://mrdemonc.github.io/PROJECT-LichUI/index.html" }
                ],
                [
                  { "text": "📦 Old Versions", "url": "https://sourceforge.net/projects/lichrom/files/SM-A546X/" }
                ],
                [
                  { "text": "📜 Changelog", "url": "https://github.com/MrDemonc/PROJECT-LichUI/blob/main/changelog.txt" }
                ],
                [
                  { "text": "📢 Credits", "url": "https://github.com/MrDemonc/PROJECT-LichUI#credits" }
                ]
              ]
            }'

      # 🏷 Create GitHub Release
      - name: Public Update
        uses: softprops/action-gh-release@v2
        with:
          name: Update ${{ env.DATE }}
          tag_name: LICH_UPDATE-${{ env.DATE }}
          body: |
            ### Update Info
            **ROM DATE:** ${{ env.DATE }}
            **OneUI Version:** 8.0

            #### ROM
            - [LichUI](https://sourceforge.net/projects/lichrom/files/SM-A546X/)

            #### Thanks for using LichUI
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
